CREATE VIEW [dbo].[table_to_be_copied]
AS
SELECT        TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM            INFORMATION_SCHEMA.TABLES
WHERE        (TABLE_TYPE = 'BASE TABLE') AND (TABLE_NAME LIKE 'KV%') AND (TABLE_NAME NOT LIKE '%1%')
