CREATE TABLE [stg].STG_StatLink_TMP_SA(

	[SL_DATE] [DATE] NULL,
	[SL_TIME] [TIME](7) NULL,
	[FILENAME][VARCHAR](900) NULL,
	[IPADDRESS] [VARCHAR](100) NULL,
	[USERAGENT] [VARCHAR](100) NULL,
	[SOURCE] [VARCHAR](900) NULL
	)