CREATE TABLE [stg].[STG_Expression_DM_SSAS_Data](
	[CurExpId] [int] NOT NULL,
	[Expression - ID] [int] NOT NULL,
	[Expression - DOI] [nvarchar](150) NULL,
	[Expression - FullTitle] [nvarchar](4000) NULL,
	[Expression - iLibraryURLAlias] [nvarchar](4000) NULL,
	[Expression - iLibraryAccessMode] [tinyint] NULL,
	[Expression - Directorate ID] [int] NOT NULL,
	[Expression - Language ID] [int] NOT NULL,
	[Expression - Theme ID] [int] NOT NULL,
	[Expression - IGO ID] [int] NOT NULL,
	[Expression - Object Type ID] [int] NOT NULL,
	[Expression - FirstRelease_Date] [datetime] NULL,
	[Expression - FirstExportDate] [datetime] NULL,
	[Expression - LatestDeletionDate] [datetime] NULL,
	[Expression - LatestExportDate] [datetime] NULL,
	[Expression - Object Type Level1] [nvarchar](150) NULL,
	[Expression - Object Type Level2] [nvarchar](150) NULL,
	[Expression - Title Level1] [nvarchar](4000) NULL,
	[Expression - Title Level2] [nvarchar](4000) NULL,
	[Expression - DOI Level1] [nvarchar](150) NULL,
	[Expression - DOI Level2] [nvarchar](150) NULL,
	[Expression - Theme Level1] [nvarchar](150) NULL,
	[Expression - Theme Level2] [nvarchar](150) NULL,
	[Expression - Directorate Code Level1] [nvarchar](4) NULL,
	[Expression - Directorate Code Level2] [nvarchar](4) NULL,
	[Expression - Directorate Name Level1] [nvarchar](150) NULL,
	[Expression - Directorate Name Level2] [nvarchar](150) NULL,
	[Expression - HasEpub] [bit] NULL,
	[Expression - HasEBook] [bit] NULL,
	[Expression - HasRead] [bit] NULL,
	[Expression - HasHTML] [bit] NULL,
	[Expression - HasExcel] [bit] NULL
)