CREATE TABLE [stg].[STG_FreePreview_TMP](
	[label] [nvarchar](2000) NULL,
	[nb_visits] [real] NULL,
	[nb_uniq_visitors] [real] NULL,
	[nb_hits] [real] NULL,
	[sum_time_spent] [real] NULL,
	[nb_hits_with_time_generation] [real] NULL,
	[min_time_generation] [real] NULL,
	[max_time_generation] [real] NULL,
	[entry_nb_uniq_visitors] [real] NULL,
	[entry_nb_visits] [real] NULL,
	[entry_nb_actions] [real] NULL,
	[entry_sum_visit_length] [real] NULL,
	[entry_bounce_count] [real] NULL,
	[exit_nb_uniq_visitors] [real] NULL,
	[exit_nb_visits] [real] NULL,
	[avg_time_on_page] [real] NULL,
	[bounce_rate] [nvarchar](50) NULL,
	[exit_rate] [nvarchar](50) NULL,
	[avg_time_generation] [real] NULL,
	[metadata_url] [nvarchar](2000) NULL,
	[sum_time_generation] [real] NULL,
    [File_Date] [date] NOT NULL,
	[Import_Date] DATETIME NOT NULL DEFAULT GETUTCDATE() 
)