CREATE TABLE [dbo].[DIM_Expression]
(
	[CurExpId] INT NOT NULL, 
    [Expression - DOI] NVARCHAR(150) NOT NULL, 
    [Expression - FullTitle] NVARCHAR(4000) NOT NULL, 
    [Expression - iLibraryURLAlias] NVARCHAR(4000) NOT NULL, 
    [Expression - Directorate ID] INT NOT NULL, 
    [Expression - Language ID] INT NOT NULL, 
    [Expression - Theme ID] INT NOT NULL, 
    [Expression - IGO ID] INT NOT NULL, 
    [Expression - Object Type ID] INT NOT NULL, 
    [Expression - FirstRelease_Date] DATETIME NULL, 
    [Expression - FirstExportDate] DATETIME NULL, 
    [Expression - LatestDeletionDate] DATETIME NULL, 
    [Expression - LatestExportDate] DATETIME NULL, 
    [Expression - Object Type Level1] NVARCHAR(150) NOT NULL, 
    [Expression - Object Type Level2] NVARCHAR(150) NOT NULL, 
    [Expression - Title Level1] NVARCHAR(4000) NOT NULL, 
    [Expression - Title Level2] NVARCHAR(4000) NOT NULL, 
    [Expression - DOI Level1] NVARCHAR(150) NOT NULL, 
    [Expression - DOI Level2] NVARCHAR(150) NOT NULL, 
    [Expression - Theme Level1] NVARCHAR(150) NOT NULL, 
    [Expression - Theme Level2] NVARCHAR(150) NOT NULL, 
    [Expression - Directorate Code Level1] NVARCHAR(4) NOT NULL, 
    [Expression - Directorate Code Level2] NVARCHAR(4) NOT NULL, 
    [Expression - Directorate Name Level1] NVARCHAR(150) NOT NULL, 
    [Expression - Directorate Name Level2] NVARCHAR(150) NOT NULL, 
    [Expression - iLibraryAccessMode] TINYINT NULL, 
    [Expression - HasEpub] BIT NOT NULL, 
    [Expression - HasEBook] BIT NOT NULL, 
    [Expression - HasExcel] BIT NOT NULL, 
    [Expression - HasRead] BIT NOT NULL, 
    [Expression - HasHTML] BIT NOT NULL 
)
