CREATE TABLE [dbo].[DIM_Expression_Metadata]
(
	[Expression_ID] INT NOT NULL, 
    [CurExpId] INT NOT NULL, 
    [DOI] NVARCHAR(100) NULL, 
    [iLibraryURLAlias] NVARCHAR(1054) NULL, 
    [iLibraryAccessMode] TINYINT NULL, 
    [FirstRelease_Date] DATETIME NULL, 
    [FullTitle] NVARCHAR(4000) NULL, 
    [FirstExportDate] DATETIME NULL, 
    [LatestDeletionDate] DATETIME NULL, 
    [LatestExportDate] DATETIME NULL, 
    [Directorate_ID] INT NOT NULL, 
    [Language_ID] INT NOT NULL, 
    [Theme_ID] INT NOT NULL, 
    [Igo_ID] INT NOT NULL, 
    [ObjectType_ID] INT NOT NULL, 
    [ISSN] NVARCHAR(20) NULL, 
    [TopParent_ID] INT NULL, 
    [Top2Parent_ID] INT NULL, 
    [Top3Parent_ID] INT NULL, 
    [HasEpub] BIT NULL, 
    [HasEBook] BIT NULL, 
    [HasRead] BIT NULL, 
    [HasHTML] BIT NULL, 
    [HasExcel] BIT NULL 
)
