CREATE PROCEDURE [stg].[SP_Truncate_STG]
AS
	
TRUNCATE TABLE [stg].[STG_BrowseIt_TMP]
TRUNCATE TABLE [stg].[STG_Metadata_TMP_CCM_Countries] 
TRUNCATE TABLE [stg].[STG_Metadata_TMP_CCM_IDS]
TRUNCATE TABLE [stg].[STG_Counter_TMP]
TRUNCATE TABLE [stg].[STG_FreePreview_TMP]
TRUNCATE TABLE [stg].[STG_GoogleBooksMonthly_TMP]
TRUNCATE TABLE [stg].[STG_ILibraryLog_TMP]
TRUNCATE TABLE [stg].[STG_Metadata_TMP_IP_Country_Range]
TRUNCATE TABLE [stg].[STG_Registration_FI]
TRUNCATE TABLE [stg].[STG_StatLink_TMP]
TRUNCATE TABLE [stg].[STG_StatLink_TMP] 
TRUNCATE TABLE [stg].[STG_StatLink_SA] 
TRUNCATE TABLE [stg].[STG_Statlink_File_SA]
TRUNCATE TABLE [stg].[STG_iLibrary_Copy_File]

TRUNCATE TABLE [stg].[KV3_Country]
TRUNCATE TABLE [stg].[KV3_CrossReferenceType]
TRUNCATE TABLE [stg].[KV3_Directorate]
TRUNCATE TABLE [stg].[KV3_ExpressionCrossReference]
TRUNCATE TABLE [stg].[KV3_Igo]
TRUNCATE TABLE [stg].[KV3_Language]
TRUNCATE TABLE [stg].[KV3_Medium]
TRUNCATE TABLE [stg].[KV3_ObjectType]
TRUNCATE TABLE [stg].[KV3_Product]
TRUNCATE TABLE [stg].[KV3_ProductDirectorate]
TRUNCATE TABLE [stg].[KV3_ProductExportChannel]
TRUNCATE TABLE [stg].[KV3_ProductLanguage]
TRUNCATE TABLE [stg].[KV3_ProductTheme]
TRUNCATE TABLE [stg].[KV3_Theme]
TRUNCATE TABLE [stg].[Statlink]

RETURN 0
